.Dd Feb 22, 2010
.Dt cplanet 1
.Os
.Sh NAME
.Nm cplanet
.Nd RSS Feed Aggregator that generate static html
.Sh SYNOPSIS
.Nm
.Op Fl l
.Fl c Ar config.hdf
.Sh DESCRIPTION
.Nm 
is a RSS/ATOM feed aggregator written in C that generate static html files.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl c Ar config.hdf
specify the path to the hdf configuration file
.It Fl l
set the log to be written in syslog, otherwise log are written to stderr
.El
.Sh CONFIGURATION FILE
.Pp
cplanet uses the clearsilver's hdf format as a configuration file, some keys are 
mandatory. Users can add as much keys as they want as they can be used in the
template file.
.Bl -tag -width indent
.It Ar CPlanet.Output.N.Path
N represents a number starting from 0, this is the patch for the file N to
generate
.It Ar CPlanet.Output.N.TemplatePath
Path of the template to use to generate the file number N
.It Ar CPlanet.Days
oldest post from the feeds to keep in days.
.It Ar CPlanet.Feed.N.Name
name of the N feed to fetch
.It Ar CPlanet.Feed.N.URL
URL of the N Feed (ATOM or RSS) to fetch.
.El
.Pp
for more informations concerning the HDF file format please refer to the
clearsilver documentation: http://www.clearsilver.net/docs/man_hdf.hdf
.Sh TEMPLATE FILE
.Nm
uses the clearsilver template system, please refer to the
clearsilver documentation: http://www.clearsilver.net/docs/man_templates.hdf
.Sh AUTHORS
Baptiste Daroussin
.Sh CONTRIBUTORS
Freddy DISSAUX
